# Generated by Django 3.1.4 on 2021-01-06 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '회원', 'verbose_name_plural': '회원'},
        ),
    ]
