# Generated by Django 3.1.4 on 2021-02-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210212_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=16, unique=True, verbose_name='닉네임'),
        ),
    ]
